---
- name: Prepare cluster installation
  hosts: k3s_cluster
  user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: docker

- name: Create k3s master
  hosts: master
  user: ubuntu
  become: yes
  roles:
    - role: k3s/master

- name: Create k3s nodes
  hosts: node
  user: ubuntu
  become: yes
  roles:
    - role: k3s/node
