- name: clone repository
  ansible.builtin.git:
    repo: https://github.com/ansible/awx-operator.git
    dest: /home/ubuntu/awx-operator
    single_branch: yes
    version: 0.21.0

- name: Export namespace
  command: export NAMESPACE=default

#- name: kustomization.yaml
#  block:
#    - file:
#        path: /home/ubuntu/{{ project_path }}
#        state: directory
#    - template:
#        src: kustomization.yml.j2
#        dest: /home/ubuntu/{{ project_path }}/kustomization.yml
#        owner: ubuntu
#        group: ubuntu
#        mode: 0644