---
- name: Checke if Helm already was installed 
  command: helm version --short
  register: helm_check_result
  failed_when: helm_check_result.rc != 0
  changed_when: false

- name: Install dependences 
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
      - lsb-release
    state: present

- name: Download script to install Helm
  get_url:
    url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
    dest: "/tmp/get-helm-3"
    mode: 0755
  when: helm_check_result.rc != 0

- name: Run the script to install Helm
  command: "/tmp/get-helm-3"
  args:
    creates: /usr/local/bin/helm
  when: helm_check_result.rc != 0
